// AUTHENTICATION MIDDLEWARES (SESSION: SIGN-IN | SING-UP | SIGN-OUT
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const ALL_TEAMS_REQUEST = 'ALL_TEAMS_REQUEST';
export const CURRENT_TEAM_REQUEST = 'CURRENT_TEAM_REQUEST';
export const NEW_TEAM_REQUEST = 'NEW_TEAM_REQUEST';
