// AUTHENTICATION MIDDLEWARES (SESSION: SIGN-IN | SING-UP | SIGN-OUT
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const USERS_REQUEST = 'USERS_REQUEST'; 