export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const CLEAR_AUTH_SUCCESS = 'CLEAR_AUTH_SUCCESS';
export const ALL_TEAMS_REQUEST = 'ALL_TEAMS_REQUEST';
export const CURRENT_TEAM_REQUEST = 'CURRENT_TEAM_REQUEST';
export const NEW_TEAM_REQUEST = 'NEW_TEAM_REQUEST';
export const USERS_REQUEST = 'USERS_REQUEST';
export const CREATE_RITE_REQUEST = 'CREATE_RITE_REQUEST';
export const CREATE_RAFFLE_REQUEST = 'CREATE_RAFFLE_REQUEST';
export const CREATE_WORKSPACE_REQUEST = 'CREATE_WORKSPACE_REQUEST';
export const WORKSPACE_CHANGES_REQUEST = 'WORKSPACE_CHANGES_REQUEST';
export const END_SYNC_REQUEST = 'END_SYNC_REQUEST';
export const SET_WORKSPACE = 'SET_WORKSPACE';
export const CLEAR_WORKSPACE = 'CLEAR_WORKSPACE';
export const RESET_WORKSPACE_SUCCESS = 'RESET_SUCCESS';
export const CLEAR_WORKSPACE_ERROR = 'CLEAR_WORKSPACE_ERROR';
export const UPDATE_WORKSPACE_REQUEST = 'UPDATE_WORKSPACE_REQUEST';
export const GET_HOOKS_REQUEST = 'GET_HOOKS_REQUEST';
export const GET_SLACK_ENTITIES_REQUEST = 'GET_SLACK_ENTITIES_REQUEST';
export const SET_HOOK_REQUEST = 'SET_HOOK_REQUEST';


