import { StyleSheet } from 'react-native';
import color from '../../styles/colors';

const styles = StyleSheet.create({
  container: {},
  buttonContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: '5%',
    // paddingLeft: '85%',
    // paddingRight: '10%',
    // width: 500,
    // alignItems: 'stretch',
    // alignContent: 'flex-end',
    // // flexDirection: 'row',
    // // alignSelf: 'flex-end',
  },
  backButton: {
    marginTop: 15,
    width: '40%',
    borderRadius: 5,
    backgroundColor: color.gray,
  },
  editButton: {
    marginTop: 15,
    width: '40%',
    borderRadius: 5,
    backgroundColor: color.blue,
  },
  screen: {
    // flex: 1,
    padding: 10,
    margin: 20,
    borderRadius: 5,
    width: '90%',
    height: 500,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.26,
    elevation: 8,
    backgroundColor: 'white',
    alignItems: 'center',
  },
  teamTitle: {
    // marginTop: 20,
    // marginBottom: 20,
    marginVertical: 15,
    fontSize: 30,
    fontWeight: 'bold',
    // padding: 10,
  },
  listOfTeam: {
    // flexDirection: 'row',
    // width: '100%',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    // alignItems: 'space-between',
    justifyContent: 'space-between',
    // padding: 10,
    // borderRadius: 5,
    // margin: 20,
  },
  cardOfMember: {
    fontSize: 16,
    width: '45%',
    height: 50,
    margin: 5,
    // justifyContent: 'space-between',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    shadowOpacity: 0.26,
    elevation: 8,
    backgroundColor: 'white',
    borderRadius: 2,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  descriptionContainer: {
    width: '100%',
    // shadowColor: 'black',
    // shadowOffset: { width: 0, height: 1 },
    // shadowRadius: 3,
    // shadowOpacity: 0.26,
    // elevation: 8,
    // backgroundColor: 'white',
    padding: 10,
    borderRadius: 5,
    margin: 20,
  },
  description: {
    fontSize: 18,

  },
  items: {
    fontSize: 16,
    textAlign: 'center',
    // padding: 10,
    // margin: 10
    // width: '50%',
  },
  chooseButtonContainer: {
    marginHorizontal: 20,
    borderRadius: 5,
    width: '90%',
    height: 50,
    backgroundColor: color.blue,
    flexDirection: 'column',
    justifyContent: 'center',
  },
});

export default { ...styles };
