import { StyleSheet } from 'react-native';
import color from '../../styles/colors';

const styles = StyleSheet.create({
  container: {},
  buttonContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: '5%',
    // paddingLeft: '85%',
    // paddingRight: '10%',
    // width: 500,
    // alignItems: 'stretch',
    // alignContent: 'flex-end',
    // // flexDirection: 'row',
    // // alignSelf: 'flex-end',
  },
  backButton: {
    marginTop: 15,
    width: '40%',
    borderRadius: 5,
    backgroundColor: color.gray,
  },
  editButton: {
    marginTop: 15,
    width: '40%',
    borderRadius: 5,
    backgroundColor: color.blue,
  },
  screen: {
    // flex: 1,
    padding: 10,
    margin: 20,
    borderRadius: 5,
    width: '90%',
    height: '70%',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.26,
    elevation: 8,
    backgroundColor: 'white',
    alignItems: 'center',
  },
  teamTitle: {
    // marginTop: 20,
    // marginBottom: 20,
    marginVertical: 15,
    fontSize: 24,
    fontWeight: 'bold',
    // padding: 10,
  },
  listOfTeam: {
    // flexDirection: 'row',
    width: '100%',
    height: "70%",
    flex: 1,
    flexDirection: 'column',
    // flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    // padding: 10,
    // borderRadius: 5,
  },
  cardOfMember: {
    fontSize: 16,
    width: '100%',
    height: "70%",
    // justifyContent: 'space-between',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    shadowOpacity: 0.26,
    elevation: 8,
    backgroundColor: 'white',
    borderRadius: 2,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  descriptionContainer: {
    width: '90%',
    // shadowColor: 'black',
    // shadowOffset: { width: 0, height: 1 },
    // shadowRadius: 3,
    // shadowOpacity: 0.26,
    // elevation: 8,
    // backgroundColor: 'white',
    padding: 10,
    borderRadius: 5,
    margin: "5%",
  },
  description: {
    fontSize: 16,

  },
  items: {
    fontSize: 16,
    textAlign: 'center',
    margin: 0,
    // padding: 10,
    // margin: 10
    // width: '50%',
  },
  chooseButtonContainer: {
    marginHorizontal: 20,
    borderRadius: 5,
    width: '90%',
    backgroundColor: color.blue,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  modal: {
    backgroundColor: color.white,
    opacity: 0.9,
    flex: 0.5,
    marginTop: '60%',
    borderRadius: 5,
  },
  modalView: {
    flex: 1,
    padding: '10%',
  },
  modalMessage: {
    fontSize: 16,
  },
  modalUser: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    paddingTop: '10%',
  },
  modalEmoji: {
    fontSize: 40,
    textAlign: 'center',
    paddingBottom: '10%',
  },
  confirmButton: {
    backgroundColor: color.blue,
    borderRadius: 5,
    marginTop: '5%',
    marginBottom: '3%',
  },
  teamCard: {
    width: '100%',
    height: "60%",
    // marginHorizontal: 20,
    // marginVertical: 10,
    justifyContent: 'center',
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.26,
    elevation: 7,
    backgroundColor: color.white,
    borderRadius: 5,
  },
  teamName: {
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    color: color.blue,
  },
});

export default { ...styles };
